services:
  fcp-fd-file-processor:
    build:
      context: .
      target: production
    image: fcp-fd-file-processor
    depends_on:
      - fcp-fd-file-processor-azurite
    container_name: fcp-fd-file-processor
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-file-processor-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      DMZ_STORAGE_ACCOUNT_NAME: ${DMZ_STORAGE_ACCOUNT_NAME:-sndfcpfdst1001dmz}
      STORAGE_USE_CONNECTION_STRING: "true"
      DMZ_STORAGE_ACCOUNT_ENDPOINT: ${DMZ_STORAGE_ACCOUNT_ENDPOINT}
    
  fcp-fd-file-processor-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: fcp-fd-file-processor-azurite