# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-processor:
    build:
      target: development
    image: fcp-fd-file-processor-development
    container_name: fcp-fd-file-processor-development
    ports:
      - "3037:3037"
      - "9037:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      USE_AZURITE: ${USE_AZURITE:-false}
      AZURITE_ACCESS_KEY: ${AZURITE_ACCESS_KEY}
      DMZ_STORAGE_ACCOUNT_NAME: ${DMZ_STORAGE_ACCOUNT_NAME}

  fcp-fd-file-processor-azurite:
    container_name: fcp-fd-file-processor-azurite-development
    environment:
      AZURITE_ACCOUNTS: "dmz:${AZURITE_ACCESS_KEY};clean:${AZURITE_ACCESS_KEY};malicious:${AZURITE_ACCESS_KEY}"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
