# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-processor:
    build:
      target: development
    image: fcp-fd-file-processor-development
    container_name: fcp-fd-file-processor-development
    ports:
      - "3019:3000"
      - "9019:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
