# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-processor:
    build:
      target: development
    image: fcp-fd-file-processor-development
    container_name: fcp-fd-file-processor-development
    ports:
      - "3037:3037"
      - "9037:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      USE_AZURITE: ${USE_AZURITE:-true}
      AZURITE_HOST: ${AZURITE_HOST:-http://fcp-fd-file-processor-azurite-development}
      AZURITE_BLOB_PORT: ${AZURITE_BLOB_PORT:-10000}
      AZURITE_ACCESS_KEY: ${AZURITE_ACCESS_KEY:-test}
      OBJECTS_CONTAINER_NAME: objects-${MESSAGE_DEV_SUFFIX}
      DMZ_STORAGE_ACCOUNT_NAME: ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}
      DMZ_STORAGE_ACCESS_KEY: ${DMZ_STORAGE_ACCESS_KEY}
      ALLOW_TEXT_FILES: ${ALLOW_TEXT_FILES:-false}

  fcp-fd-file-processor-azurite:
    container_name: fcp-fd-file-processor-azurite-development
    environment:
      AZURITE_ACCOUNTS: >
        ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}:${AZURITE_ACCESS_KEY:-test};${CLN_STORAGE_ACCOUNT_NAME:-cln}:${AZURITE_ACCESS_KEY:-test};${MAL_STORAGE_ACCOUNT_NAME:-mal}:${AZURITE_ACCESS_KEY:-test}
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
