apiVersion: v2
description: File Processor for front door
name: fcp-fd-file-processor
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.2.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
