{{- include "ffc-helm-library.container-config-map" (list . "fcp-fd-file-processor.config-map") -}}
{{- define "fcp-fd-file-processor.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  DMZ_STORAGE_ACCOUNT_NAME: {{ .Values.container.dmzStorageAccountName }}
  AV_SCAN_POLLING_INTERVAL: {{ .Values.container.avScanPollingInterval }}
  AV_SCAN_MAX_ATTEMPTS: {{ .Values.container.avScanMaxAttempts }}
  MANAGED_IDENTITY_CLIENT_ID: {{ quote .Values.azureIdentity.clientID }}
{{- end -}}
