{{- include "ffc-helm-library.container-secret" (list . "fcp-fd-file-processor.container-secret") -}}
{{- define "fcp-fd-file-processor.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
